# Generated by Django 4.2.5 on 2023-10-05 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(max_length=10, verbose_name='code postal')),
                ('city', models.CharField(max_length=80, verbose_name='ville')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone français valide, ex: 0123456789.', regex='^0[1-9](\\d{8})$')], verbose_name='numéro de téléphone')),
                ('contact_email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(message="L'adresse email est invalide.")], verbose_name='email de contact')),
            ],
            options={
                'verbose_name': 'garage',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'type de service',
                'verbose_name_plural': 'types de service',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('price', models.PositiveIntegerField(verbose_name='prix')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('km', models.PositiveIntegerField(verbose_name='kilométrage')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.PROTECT, to='garage.garage', verbose_name='garage')),
            ],
            options={
                'verbose_name': 'véhicule',
            },
        ),
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='photos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='garage.vehicle')),
            ],
            options={
                'verbose_name': "photo d'un véhicule",
                'verbose_name_plural': 'photos des véhicules',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.PROTECT, to='garage.garage', verbose_name='garage')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_name', to='garage.servicetype')),
            ],
            options={
                'verbose_name': 'service',
            },
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lun.', 'Lundi'), ('Mar.', 'Mardi'), ('Mer.', 'Mercredi'), ('Jeu.', 'Jeudi'), ('Ven.', 'Vendredi'), ('Sam.', 'Samedi'), ('Dim.', 'Dimanche')], max_length=10, verbose_name='jour de la semaine')),
                ('opening_hours', models.CharField(max_length=80, verbose_name="horaires d'ouverture")),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.PROTECT, to='garage.garage', verbose_name='garage')),
            ],
            options={
                'verbose_name': 'horaire',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('message', models.TextField(max_length=2000, verbose_name='message')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='La note maximale est 5 étoiles.'), django.core.validators.MinValueValidator(0, message='La note minimale est 0 étoile.')], verbose_name='note')),
                ('valid', models.BooleanField(null=True, verbose_name='valide')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de réception')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.PROTECT, to='garage.garage', verbose_name='garage')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'témoignage client',
                'verbose_name_plural': 'témoignages client',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Entrez une adresse email valide.')], verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Entrez un numéro de téléphone français valide, ex: 0123456789.', regex='^0[1-9](\\d{8})$')], verbose_name='numéro de téléphone')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='sujet')),
                ('message', models.TextField(max_length=5000, verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de réception')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.PROTECT, to='garage.garage', verbose_name='garage')),
            ],
            options={
                'verbose_name': 'message client',
                'verbose_name_plural': 'messages client',
            },
        ),
    ]
