# Generated by Django 4.2.3 on 2023-07-16 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='prénom')),
                ('lastname', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('phone_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Saisissez un numéro de téléphone valide, ex: 0123456789.', regex='^0[1-9](\\d{8})$')], verbose_name='numéro de téléphone')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='sujet')),
                ('message', models.TextField(max_length=5000, verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de réception')),
            ],
            options={
                'verbose_name': 'Messages client',
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nom')),
                ('message', models.TextField(max_length=2000, verbose_name='message')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='note')),
                ('verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('valid', models.BooleanField(null=True, verbose_name='valide')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de réception')),
            ],
            options={
                'verbose_name': 'Témoignages client',
            },
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nom')),
                ('adress', models.CharField(max_length=255, verbose_name='adresse')),
                ('postal_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=80, verbose_name='ville')),
                ('phone_number', models.CharField(max_length=30, verbose_name='numéro de téléphone')),
                ('contact_email', models.CharField(max_length=80, verbose_name='email de contact')),
            ],
            options={
                'verbose_name': 'Garage',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('price', models.CharField(max_length=80, verbose_name='prix')),
                ('year', models.SmallIntegerField(verbose_name='année')),
                ('km', models.IntegerField(verbose_name='kilométrage')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
            options={
                'verbose_name': 'Véhicule',
            },
        ),
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='photos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='garage.vehicle')),
            ],
            options={
                'verbose_name': 'Photos des véhicule',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='image')),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
            options={
                'verbose_name': 'Types de service',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_name', to='garage.servicetype')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('day', models.CharField(choices=[('Lun.', 'Lundi'), ('Mar.', 'Mardi'), ('Mer.', 'Mercredi'), ('Jeu.', 'Jeudi'), ('Ven.', 'Vendredi'), ('Sam.', 'Samedi'), ('Dim.', 'Dimanche')], max_length=10, primary_key=True, serialize=False, verbose_name='jour de la semaine')),
                ('opening_hours', models.CharField(max_length=80, verbose_name="horaires d'ouverture")),
                ('garage', models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
            options={
                'verbose_name': 'Horaire',
            },
        ),
    ]
