# Generated by Django 4.2.3 on 2023-07-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='prénom')),
                ('lastname', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(max_length=80, verbose_name='email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='numéro de téléphone')),
                ('subject', models.CharField(max_length=254, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('date', models.DateTimeField(verbose_name="date d'envoi")),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nom')),
                ('message', models.TextField(verbose_name='message')),
                ('rating', models.SmallIntegerField(verbose_name='note')),
                ('verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('valid', models.BooleanField(null=True, verbose_name='valide')),
                ('date', models.DateTimeField(verbose_name="date d'envoi")),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='nom')),
                ('adress', models.CharField(max_length=254, verbose_name='adresse')),
                ('postal_code', models.CharField(max_length=20, verbose_name='code postal')),
                ('city', models.CharField(max_length=80, verbose_name='ville')),
                ('phone_number', models.CharField(max_length=30, verbose_name='numéro de téléphone')),
                ('contact_email', models.CharField(max_length=80, verbose_name='email de contact')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('price', models.CharField(max_length=80, verbose_name='prix')),
                ('year', models.SmallIntegerField(verbose_name='année')),
                ('km', models.IntegerField(verbose_name='kilométrageé')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='photos')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTime',
            fields=[
                ('day', models.CharField(choices=[('monday', 'lundi'), ('tuesday', 'mardi'), ('wednesday', 'mercredi'), ('thursday', 'jeudi'), ('friday', 'vendredi'), ('saturday', 'samedi'), ('sunday', 'dimanche')], max_length=10, primary_key=True, serialize=False, verbose_name='jour de la semaine')),
                ('opening_hours', models.CharField(max_length=80, verbose_name="horaires d'ouverture")),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
        ),
    ]
