# Generated by Django 4.2.6 on 2023-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default='marque', max_length=50, verbose_name='marque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='energy',
            field=models.CharField(default='énergie', max_length=50, verbose_name='énergie'),
            preserve_default=False,
        ),
    ]
