# Generated by Django 4.2.3 on 2023-07-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='adresse'),
        ),
    ]
