# Generated by Django 4.2.5 on 2023-10-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
