# Generated by Django 4.2.3 on 2023-07-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_alter_customermessage_subject_alter_garage_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi"),
        ),
    ]
