# Generated by Django 4.2.6 on 2023-10-12 15:39

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_customerreview_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'2xl': 1536, 'lg': 1024, 'md': 768, 'sm': 640, 'xl': 1280}, container_width=1280, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='uploads/%Y/%m/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='picture',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'2xl': 1536, 'lg': 1024, 'md': 768, 'sm': 640, 'xl': 1280}, container_width=1280, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='uploads/%Y/%m/', verbose_name='photos'),
        ),
    ]
