# Generated by Django 4.2.3 on 2023-07-14 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_customermessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^0[1-9](\\d{8})$')], verbose_name='numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi"),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='note'),
        ),
    ]
