# Generated by Django 4.2.6 on 2023-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=24, verbose_name='nom'),
        ),
    ]
