# Generated by Django 4.2.6 on 2023-11-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='couleur', max_length=30, verbose_name='couleur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='critair',
            field=models.PositiveIntegerField(default=0, verbose_name="crit'air"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(default='Automatique', max_length=30, verbose_name='boîte de vitesse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.PositiveIntegerField(default=5, verbose_name='puissance (cv)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(default=5, verbose_name='nombre de places'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='marque'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='energy',
            field=models.CharField(max_length=30, verbose_name='énergie'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=30, verbose_name='modèle'),
        ),
    ]
