# Generated by Django 4.2.3 on 2023-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_customermessage_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='message'),
        ),
    ]
