# Generated by Django 4.2.6 on 2023-10-12 20:09

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_servicetype_image_alter_vehiclepicture_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'2xl': 1536, 'lg': 1024, 'md': 768, 'sm': 640, 'xl': 1280}, container_width=1280, file_types=['WEBP'], grid_columns=12, height_field='picture_height', pixel_densities=[1, 2], upload_to='uploads/%Y/%m/', verbose_name='image', width_field='picture_width'),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='picture',
            field=pictures.models.PictureField(aspect_ratios=[None], breakpoints={'2xl': 1536, 'lg': 1024, 'md': 768, 'sm': 640, 'xl': 1280}, container_width=1280, file_types=['WEBP'], grid_columns=12, height_field='picture_height', pixel_densities=[1, 2], upload_to='uploads/%Y/%m/', verbose_name='photos', width_field='picture_width'),
        ),
    ]
