# Generated by Django 4.2.7 on 2023-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_vehicle_color_vehicle_critair_vehicle_gearbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='picture',
            field=models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='photos'),
        ),
    ]
