# Generated by Django 4.2.3 on 2023-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_customerreview_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de réception'),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de réception'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='km',
            field=models.IntegerField(verbose_name='kilométrage'),
        ),
    ]
