# Generated by Django 4.2.3 on 2023-07-14 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_customermessage_date_alter_customerreview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='phone_number',
            field=models.CharField(help_text='ex: 0102030405', max_length=30, validators=[django.core.validators.RegexValidator(message='Saisissez un numéro de téléphone valide', regex='^0[1-9](\\d{8})$')], verbose_name='numéro de téléphone'),
        ),
    ]
