# Generated by Django 4.2.3 on 2023-07-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_customermessage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sujet'),
        ),
    ]
