# Generated by Django 4.2.3 on 2023-07-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_alter_customermessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/', verbose_name='image'),
        ),
    ]
