# Generated by Django 4.2.3 on 2023-07-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/', verbose_name='image')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.garage')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.servicetype'),
        ),
    ]
