# Generated by Django 4.2.3 on 2023-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_remove_service_garage_remove_service_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessage',
            options={'verbose_name': 'Messages client'},
        ),
        migrations.AlterModelOptions(
            name='customerreview',
            options={'verbose_name': 'Témoignages client'},
        ),
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Garage'},
        ),
        migrations.AlterModelOptions(
            name='openingtime',
            options={'verbose_name': 'Horaire'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Types de service'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Véhicule'},
        ),
        migrations.AlterModelOptions(
            name='vehiclepicture',
            options={'verbose_name': 'Photos des véhicule'},
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='day',
            field=models.CharField(choices=[('lundi', 'Monday'), ('mardi', 'Tuesday'), ('mercredi', 'Wednesday'), ('jeudi', 'Thursday'), ('vendredi', 'Friday'), ('samedi', 'Saturday'), ('dimanche', 'Sunday')], max_length=10, primary_key=True, serialize=False, verbose_name='jour de la semaine'),
        ),
    ]
