# Generated by Django 4.2.3 on 2023-07-16 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0013_alter_customermessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='day',
            field=models.CharField(choices=[('Lun.', 'Lundi'), ('Mar.', 'Mardi'), ('Mer.', 'Mercredi'), ('Jeu.', 'Jeudi'), ('Ven.', 'Vendredi'), ('Sam.', 'Samedi'), ('Dim.', 'Dimanche')], max_length=10, primary_key=True, serialize=False, verbose_name='jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='openingtime',
            name='garage',
            field=models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='garage',
            field=models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(default='Garage.objects.first()', on_delete=django.db.models.deletion.CASCADE, to='garage.garage'),
        ),
    ]
