BEGIN;
--
-- Create model CustomerMessage
--
CREATE TABLE "garage_customermessage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "firstname" varchar(80) NOT NULL, "lastname" varchar(80) NOT NULL, "email" varchar(80) NOT NULL, "phone_number" varchar(30) NOT NULL, "subject" varchar(255) NULL, "message" text NOT NULL, "date" timestamp with time zone NOT NULL);
--
-- Create model CustomerReview
--
CREATE TABLE "garage_customerreview" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(20) NOT NULL, "message" text NOT NULL, "rating" smallint NOT NULL, "verified" boolean NOT NULL, "valid" boolean NULL, "date" timestamp with time zone NOT NULL);
--
-- Create model Garage
--
CREATE TABLE "garage_garage" ("name" varchar(50) NOT NULL PRIMARY KEY, "adress" varchar(255) NOT NULL, "postal_code" varchar(20) NOT NULL, "city" varchar(80) NOT NULL, "phone_number" varchar(30) NOT NULL, "contact_email" varchar(80) NOT NULL);
--
-- Create model Vehicle
--
CREATE TABLE "garage_vehicle" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL, "price" varchar(80) NOT NULL, "year" smallint NOT NULL, "km" integer NOT NULL, "garage_id" varchar(50) NOT NULL);
--
-- Create model VehiclePicture
--
CREATE TABLE "garage_vehiclepicture" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "picture" varchar(100) NOT NULL, "vehicle_id" bigint NOT NULL);
--
-- Create model ServiceType
--
CREATE TABLE "garage_servicetype" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "image" varchar(100) NOT NULL, "garage_id" varchar(50) NOT NULL);
--
-- Create model Service
--
CREATE TABLE "garage_service" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL, "type_id" bigint NOT NULL);
--
-- Create model OpeningTime
--
CREATE TABLE "garage_openingtime" ("day" varchar(10) NOT NULL PRIMARY KEY, "opening_hours" varchar(80) NOT NULL, "garage_id" varchar(50) NOT NULL);
CREATE INDEX "garage_garage_name_260c2149_like" ON "garage_garage" ("name" varchar_pattern_ops);
ALTER TABLE "garage_vehicle" ADD CONSTRAINT "garage_vehicle_garage_id_5fe89587_fk_garage_garage_name" FOREIGN KEY ("garage_id") REFERENCES "garage_garage" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "garage_vehicle_garage_id_5fe89587" ON "garage_vehicle" ("garage_id");
CREATE INDEX "garage_vehicle_garage_id_5fe89587_like" ON "garage_vehicle" ("garage_id" varchar_pattern_ops);
ALTER TABLE "garage_vehiclepicture" ADD CONSTRAINT "garage_vehiclepicture_vehicle_id_8e525a55_fk_garage_vehicle_id" FOREIGN KEY ("vehicle_id") REFERENCES "garage_vehicle" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "garage_vehiclepicture_vehicle_id_8e525a55" ON "garage_vehiclepicture" ("vehicle_id");
ALTER TABLE "garage_servicetype" ADD CONSTRAINT "garage_servicetype_garage_id_1cdb1954_fk_garage_garage_name" FOREIGN KEY ("garage_id") REFERENCES "garage_garage" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "garage_servicetype_garage_id_1cdb1954" ON "garage_servicetype" ("garage_id");
CREATE INDEX "garage_servicetype_garage_id_1cdb1954_like" ON "garage_servicetype" ("garage_id" varchar_pattern_ops);
ALTER TABLE "garage_service" ADD CONSTRAINT "garage_service_type_id_ba0a8e92_fk_garage_servicetype_id" FOREIGN KEY ("type_id") REFERENCES "garage_servicetype" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "garage_service_type_id_ba0a8e92" ON "garage_service" ("type_id");
ALTER TABLE "garage_openingtime" ADD CONSTRAINT "garage_openingtime_garage_id_ba029141_fk_garage_garage_name" FOREIGN KEY ("garage_id") REFERENCES "garage_garage" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "garage_openingtime_day_263245f1_like" ON "garage_openingtime" ("day" varchar_pattern_ops);
CREATE INDEX "garage_openingtime_garage_id_ba029141" ON "garage_openingtime" ("garage_id");
CREATE INDEX "garage_openingtime_garage_id_ba029141_like" ON "garage_openingtime" ("garage_id" varchar_pattern_ops);
COMMIT;
